name: cezoo
favicon: null
layout_spectrum: 0.8919731590431184
typography_spectrum: 0.2642152300104499
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8783710794523358
  lightness: 0.8482045794371516
  saturation: 0.11288900510407984
  rhythmicContrast: 0.5412817865144461
purpose: []
